project:
  type: website

website:
  title: albertprofe wiki
  cookie-consent:
    type: express
    style: headline
    palette: dark

  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]

  navbar:
    background: dark
    style: "floating"
    search: true
    
    right:
      - text: Home
        file: index.qmd
      - sidebar:linux
      - sidebar:markup
      - sidebar:javase
      - sidebar:spring   
      - sidebar:reactjs
      - sidebar:scrum
      - sidebar:devops
      - sidebar:vocabulary
      - sidebar:ifcd
      - sidebar:about

  sidebar:
    - id: "devops"
      title: "DevOps"
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents:
        - text: "DevOps"
        - text: "---"  
        - section: "What is DevOps"
          contents: 
            - devops/introductiondevops.qmd
            - devops/devops.qmd
        - text: "---"  
        - section: "Documentation"
          contents: 
            - devops/quarto.qmd
        - text: "---"  
        - section: "Version Control"
          contents: 
            - devops/git.qmd
            - devops/github.qmd
        - text: "---" 
        - section: "IDEs"
          contents: 
            - devops/visualcode.qmd
            - devops/intelljidea.qmd
        - text: "---"           
        - section: "DevOps tools"
          contents:
            - devops/aws.qmd 
            - devops/docker.qmd
            - devops/jenkins.qmd
            - devops/k8s.qmd
            - devops/digitalocean.qmd
            - devops/installjenkins.qmd
            - devops/installmaven.qmd
        - text: "---"      
        - section: "DevOps Laboratories"
          contents: 
            - devops/chatapp.qmd
            - devops/springbooksintro.qmd
            - devops/springbookss3.qmd
            - devops/springbooksdocker.qmd
            - devops/k8sdigitalocean.qmd
        - text: "---"  
        - section: "DevOps readings"
          contents: 
            - devops/resources.qmd

    - id: "linux"
      title: "Linux OS"
      contents: 
        - text: "Linux OS"
        - text: "---"  
        - section: "Linux: concepts"
          contents: 
            - linux/linux-what-basics.qmd
            - linux/linux-what-vm.qmd
        - text: "---"  
        - section: "Linux: distros"
          contents: 
            - linux/linux-distros-mint.qmd
            - linux/linux-distros-debian.qmd
            - linux/linux-distros-opensuse.qmd
            
    - id: "markup"
      title: "MarkUp"
      contents: 
        - text: "MarkUp Languages and Styling"
        - text: "---"  
        - section: "MarkUp Languages"
          contents: 
            - markup/markupintro.qmd
            - markup/markuphtml.qmd
            - markup/markupdown.qmd
            - markup/markuphtmlrelation.qmd
        - text: "---"  
        - section: "Quarto Markdown"
          contents: 
            - markup/markupquarto.qmd
            - markup/markupquartocreating.qmd
            - markup/markupquartopublishing.qmd
            - markup/markupquartoprogramming.qmd
        - text: "---"  
        - section: "Styling: CSS"
          contents: 
            - markup/markupcss.qmd
            - markup/markupw3css.qmd
        - text: "---"  
        - section: "MarkUp Languages Laboratories"
          contents: 
            - markup/mulab1.qmd
        - text: "---" 
        - section: "MarkUp Langjavaseuages readings"
          contents: 
            - markup/resources.qmd
            
    - id: "scrum"
      title: "SCRUM"
      contents: 
        - text: "SCRUM"
        - text: "---"  
        - section: "What is SCRUM"
          contents: 
            - scrum/scrum.qmd
            - scrum/agilemanifesto.qmd
            - scrum/scrumguide.qmd
            - scrum/digitaltoolsscrum.qmd
        - text: "---"  
        - section: "Weeks"
          contents: 
            - scrum/week1.qmd
            - scrum/week2.qmd
            - scrum/week3.qmd
            - scrum/week4.qmd
            - scrum/week5.qmd
 
    - id: "javase"
      title: "Java SE"
      contents: 
        - text: "Java Standard Edition"
        - text: "---"  
        - section: "What is Java SE"
          contents: 
            - javase/se-what-basics.qmd
            - javase/se-what-principles.qmd
            - javase/se-what-moochelsinki.qmd
        - text: "---"
        - section: "Java Concepts"
          contents:
            - javase/se-concepts-maven.qmd
            - javase/se-concepts-createproject.qmd
            - javase/se-concepts-tdd.qmd
            - javase/se-concepts-objects.qmd
            - javase/se-concepts-scope.qmd
            - javase/se-concepts-static.qmd
            - javase/se-concepts-coupling.qmd
            - javase/se-concepts-package.qmd
        - text: "---"
        - section: "Java Principles"
          contents:
            - javase/se-principles-encapsulation.qmd
            - javase/se-principles-abstraction.qmd
            - javase/se-principles-inheritance.qmd
            - javase/se-principles-polymorphism.qmd    
        - text: "---"  
        - section: "Java Design Patterns"
          contents: 
            - javase/se-pattern-intro.qmd
            - javase/se-pattern-singleton.qmd
            - javase/se-pattern-factory.qmd
            - javase/se-pattern-abstractfactory.qmd
            - javase/se-pattern-observer.qmd
            - javase/se-pattern-builder.qmd
        - text: "---"  
        - section: "Java SE Laboratories"
          contents: 
            - javase/selab1-1.qmd
            - javase/selab1-2.qmd
            - javase/selab3.qmd
            - javase/selab4.qmd
            - javase/selab5.qmd
        - text: "---" 
        - section: "Java SE readings"
          contents: 
            - javase/resources.qmd

    - id: "spring"
      title: "Spring"
      contents:
        - text: "Spring"
        - text: "---"  
        - section: "Spring Legacy"
          contents: 
            - spring/spring.qmd
            - spring/springmvc.qmd
        - text: "---"  
        - section: "Spring Boot"
          contents: 
            - springboot/springboot.qmd
        - text: "---"  
        - section: "Spring Boot Laboratories"
          contents: 
            - springboot/sblab1.qmd
            - springboot/sblab2.qmd
            - springboot/sblab3.qmd
            - springboot/sblab4.qmd
            - springboot/sblab5.qmd
        - text: "---" 
        - section: "Spring Boot readings"
          contents: 
            - springboot/resources.qmd
        
    - id: "reactjs"
      title: "React JS"
      contents: 
        - text: "React JS"
        - text: "---"  
        - section: "React JS Principles"
          contents: 
            - reactjs/reactjs.qmd
        - section: "React JS Hooks"
          contents: 
            - reactjs/hookstate.qmd
            - reactjs/hookreducer.qmd
            - reactjs/hookref.qmd
            - reactjs/hookeffect.qmd
            - reactjs/hookcustom.qmd
        - text: "---"  
        - section: "Context and Provider"
          contents: 
            - reactjs/reactjscontext.qmd
        - text: "---"  
        - section: "React JS Laboratories"
          contents: 
            - reactjs/rjslab1.qmd
            - reactjs/rjslab2.qmd
            - reactjs/rjslab3.qmd
            - reactjs/rjslab4.qmd
            - reactjs/rjslab5.qmd
        - text: "---" 
        - section: "React JS readings"
          contents: 
            - reactjs/resources.qmd

    
    - id: "ifcd"
      title: "IFCD0210"
      contents: 
        - text: "IFCD0210"
        - text: "---"  
        - section: "Web App IFCD0210"
          contents: 
            - ifcd0210/ifcd0210.qmd
            - ifcd0210/ifcd0210calendar.qmd  
            - ifcd0210/ifcd0210initemail.qmd  
            - ifcd0210/ifcd0210deliveries.qmd  
        
    - id: "vocabulary"
      title: "Vocabulary"
      contents: 
        - text: "Vocabulary"
        - text: "---"  
        - section: "General Vocabulary"
          contents: 
            - vocabulary/vocabgeneral.qmd
            - vocabulary/vocabscrum.qmd
            - vocabulary/vocabdevops.qmd
        - text: "---"  
        - section: "Back-end Vocabulary"
          contents: 
            - vocabulary/vocabjava.qmd
            - vocabulary/vocabspringboot.qmd
            - vocabulary/vocabdatabase.qmd
        - text: "---"  
        - section: "Front-end Vocabulary"
          contents: 
            - vocabulary/vocabreactjs.qmd 
            - vocabulary/vocabweb.qmd          

    - id: "about"
      title: "About"
      contents: 
        - text: "About"
        - text: "---"  
        - section: "About"
          contents: 
            - about/aboutme.qmd
            - about/aboutthissite.qmd
            - about/aboutlearning.qmd
            - about/aboutimagescredit.qmd 
            - about/aboutquestions.qmd                   
  
  
  page-footer: 
    background: dark
    left: "[Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)" 
    center: "if you want to go far, walk slow" 
    right: 
      - icon: github
        href: https://github.com/AlbertProfe/
      - icon: twitter 
        href: https://twitter.com/ 

format:
  html:
    fontsize:  "1.0em"
    theme:
      light: default
      dark: superhero
    css: styles.css
    toc: true
    toc-depth: 5
    email-obfuscation: javascript
    
execute:
  cache: true
  freeze: auto



